(()=>{
'use strict';
window.MIMMO_BINARI_V22=true;
const COLS=8, ROWS=12, CELL=60, MATCH=4;
const COLORS=[
 {name:'Rosso',a:'#ff5a5f',b:'#c91835',rim:'#7b1021'},
 {name:'Blu',a:'#55b9ff',b:'#176bd3',rim:'#0b3c82'},
 {name:'Verde',a:'#6bdc75',b:'#1d9f54',rim:'#0c6633'},
 {name:'Giallo',a:'#ffe36e',b:'#e5a514',rim:'#916300'},
 {name:'Viola',a:'#c186ff',b:'#7545c7',rim:'#48257f'}
];
const SYMBOLS=['circle','triangle','diamond','square','star'];
const WORLD_NAMES=['Ardore','Costa Calabrese','Stretto','Sud Italia','Campania','Roma','Lazio → Toscana','Valdarno','Firenze','Firenze S.M.N.'];
const WORLD_BG=['assets/stations/st01_ardore.jpg','assets/stations/st02_bovalino.jpg','assets/stations/st03_locri.jpg','assets/stations/st04_gioiosa.jpg','assets/stations/st05_siderno.jpg','assets/stations/st14_ferrovia.jpg','assets/stations/st12_toscana.jpg','assets/stations/st07_figline.jpg','assets/stations/st16_laurea.jpg','assets/stations/st17_pensione.jpg'];
const $=s=>document.querySelector(s), sleep=ms=>new Promise(r=>setTimeout(r,ms));
const canvas=$('#binariCanvas'), ctx=canvas.getContext('2d');
const nextCanvas=$('#bpNext'), nctx=nextCanvas.getContext('2d');
const state={board:Array.from({length:ROWS},()=>Array(COLS).fill(null)),active:null,next:null,score:0,locked:0,obstacles:0,breakables:0,pieces:0,comboMax:0,running:false,resolving:false,paused:false,lastDrop:0,dropMs:780,baseDropMs:780,slowPieces:0,fastPieces:0,fogTurns:0,flash:new Set(),shake:new Set(),level:1,cfg:null,tutorialStep:0,inputStart:null};
let idSeq=1,raf=0;
function rng(seed){let s=seed>>>0;return()=>((s=(s*1664525+1013904223)>>>0)/4294967296)}
function levelCfg(level){
 const world=Math.min(10,Math.ceil(level/10)); const band=Math.floor((level-1)/5); const local=(level-1)%10+1;
 let colors=2,symbols=2,locked=3+Math.floor((level-1)/2),obstacles=0,breakables=0,bonusChance=0,malus=null,shape='open';
 if(level>=6){colors=3;symbols=3;locked=5+Math.floor((level-6)/3)}
 if(level>=11) obstacles=Math.min(7,1+Math.floor((level-11)/3));
 if(level>=16) breakables=Math.min(8,1+Math.floor((level-16)/3));
 if(level>=21) bonusChance=Math.min(.22,.08+(level-21)*.004);
 if(level>=26) malus= level<36?'fog':level<51?'delay':level<71?'signal':'mixed';
 if(level>=31) shape=(level%3===0?'notch':level%3===1?'pillars':'open');
 colors=Math.min(5,colors+(level>=41?1:0)+(level>=71?1:0)); symbols=Math.min(5,symbols+(level>=51?1:0)+(level>=81?1:0));
 const speed=Math.max(250,820-level*4-(level>70?(level-70)*4:0));
 return {level,world,local,colors,symbols,locked:Math.min(20,locked),obstacles,breakables,bonusChance,malus,shape,speed,
  name:`${WORLD_NAMES[world-1]} • Tratta ${local}`,
  objective: level<11?'Libera tutti i vagoni bloccati': level<16?'Libera i vagoni e supera gli ostacoli': level<21?'Libera i vagoni e rompi i blocchi': 'Completa la tratta e sfrutta i bonus'};
}
function empty(){return Array.from({length:ROWS},()=>Array(COLS).fill(null))}
function makeWagon(color,symbol,kind='normal',extra={}){return {id:idSeq++,kind,color,symbol,linkId:null,hp:1,...extra}}
function posCells(piece,r=piece.r,c=piece.c,o=piece.o){const d=[[0,1],[1,0],[0,-1],[-1,0]][o];return [{r,c,u:piece.units[0]},{r:r+d[0],c:c+d[1],u:piece.units[1]}]}
function inBounds(r,c){return r>=0&&r<ROWS&&c>=0&&c<COLS}
function valid(piece,r=piece.r,c=piece.c,o=piece.o){return posCells(piece,r,c,o).every(p=>inBounds(p.r,p.c)&&!state.board[p.r][p.c])}
function makeUnit(){const cfg=state.cfg,rr=state._rng;let bonus=null;if(cfg.level>=21&&rr()<cfg.bonusChance){const x=rr();bonus=x<.45?'bomb':x<.75?'loco':'clock'}return {color:Math.floor(rr()*cfg.colors),symbol:Math.floor(rr()*cfg.symbols),bonus}}
function makePair(){if(state.level===1&&state.pieces===0)return {r:0,c:3,o:0,units:[{color:0,symbol:0,bonus:null},{color:1,symbol:1,bonus:null}]};return {r:0,c:3,o:0,units:[makeUnit(),makeUnit()]}}
function blockedCellsForShape(cfg){const set=new Set();if(cfg.shape==='notch'){for(let r=8;r<ROWS;r++){if(r===8){set.add(`${r},0`);set.add(`${r},7`)}if(r===9){set.add(`${r},0`);set.add(`${r},7`)}}}if(cfg.shape==='pillars'){for(let r=7;r<ROWS;r++){if(r%2===1){set.add(`${r},0`);set.add(`${r},7`)}}}return set}
function buildLevel(level){
 state.level=level;state.cfg=levelCfg(level);state._rng=rng(level*991+17);state.board=empty();state.score=0;state.pieces=0;state.comboMax=0;state.resolving=false;state.running=true;state.paused=false;state.slowPieces=0;state.fastPieces=0;state.fogTurns=0;state.flash.clear();state.shake.clear();state.dropMs=state.baseDropMs=state.cfg.speed;
 const fixed=blockedCellsForShape(state.cfg); fixed.forEach(k=>{const [r,c]=k.split(',').map(Number);state.board[r][c]={id:idSeq++,kind:'obstacle',variant:'concrete',hp:99,fixed:true}});
 if(level===1){[[11,2],[11,3],[11,4]].forEach(([r,c])=>state.board[r][c]=makeWagon(0,0,'locked'));[[10,6],[9,6],[8,6]].forEach(([r,c])=>state.board[r][c]=makeWagon(1,1,'locked'));}
 else placeLocked(state.cfg.locked);
 placeStatic('obstacle',state.cfg.obstacles);placeStatic('breakable',state.cfg.breakables);
 recount(); state.next=makePair(); spawn(); updateUI(); setWorld(); tutorialForLevel();
}
function openCellCandidates(minRow=4){const a=[];for(let r=minRow;r<ROWS;r++)for(let c=0;c<COLS;c++)if(!state.board[r][c])a.push([r,c]);return a}
function placeLocked(n){let cells=openCellCandidates(5),rr=state._rng;for(let i=0;i<n&&cells.length;i++){let idx=Math.floor(rr()*cells.length),[r,c]=cells.splice(idx,1)[0];state.board[r][c]=makeWagon(Math.floor(rr()*state.cfg.colors),Math.floor(rr()*state.cfg.symbols),'locked')}}
function placeStatic(kind,n){let cells=openCellCandidates(6),rr=state._rng;for(let i=0;i<n&&cells.length;i++){let idx=Math.floor(rr()*cells.length),[r,c]=cells.splice(idx,1)[0];state.board[r][c]={id:idSeq++,kind,variant:kind==='obstacle'?(rr()<.5?'barrier':'rock'):'crate',hp:kind==='breakable'?(2+Math.floor(rr()*2)):(state.level>50&&rr()<.35?2:1),fixed:true}}}
function recount(){state.locked=0;state.obstacles=0;state.breakables=0;for(const row of state.board)for(const x of row)if(x){if(x.kind==='locked')state.locked++;if(x.kind==='obstacle'&&x.hp<90)state.obstacles++;if(x.kind==='breakable')state.breakables++}}
function spawn(){state.active=state.next||makePair();state.active.r=0;state.active.c=3;state.active.o=0;state.next=makePair();state.pieces++;applyTimedEffects();if(!valid(state.active)){gameOver();return}drawNext();state.lastDrop=performance.now();}
function applyTimedEffects(){if(state.slowPieces>0){state.slowPieces--;state.dropMs=Math.round(state.baseDropMs*1.35)}else if(state.fastPieces>0){state.fastPieces--;state.dropMs=Math.round(state.baseDropMs*.68)}else state.dropMs=state.baseDropMs;if(state.fogTurns>0)state.fogTurns--;if(state.cfg.malus&&state.pieces>0&&state.pieces%8===0){triggerMalus(state.cfg.malus)}}
function triggerMalus(type){const t=type==='mixed'?(['fog','delay','signal'][Math.floor(state._rng()*3)]):type;if(t==='fog'){state.fogTurns=3;toast('🌫️ Nebbia: alcuni vagoni sono meno leggibili');}if(t==='delay'){state.fastPieces=3;toast('⏱️ Ritardo: la caduta accelera per 3 pezzi');}if(t==='signal'){let cells=openCellCandidates(4);if(cells.length){const [r,c]=cells[Math.floor(state._rng()*cells.length)];state.board[r][c]={id:idSeq++,kind:'obstacle',variant:'barrier',hp:1,fixed:true};recount();toast('🚧 Semaforo rosso: nuovo ostacolo!')}}}
function move(dx,dy){if(!state.running||state.resolving||state.paused)return false;let p=state.active;if(valid(p,p.r+dy,p.c+dx,p.o)){p.r+=dy;p.c+=dx;haptic(5);return true}return false}
function rotate(dir=1){if(!state.running||state.resolving||state.paused)return;let p=state.active,no=(p.o+(dir>0?1:3))%4;for(const [kr,kc] of [[0,0],[0,-1],[0,1],[-1,0],[1,0]])if(valid(p,p.r+kr,p.c+kc,no)){p.r+=kr;p.c+=kc;p.o=no;sfx('clack');haptic(6);return}}
function hardDrop(){if(!state.running||state.resolving||state.paused)return;let n=0;while(move(0,1))n++;state.score+=n*2;lockPiece()}
async function lockPiece(){if(state.resolving||!state.active)return;state.resolving=true;const link=idSeq++;for(const p of posCells(state.active)){state.board[p.r][p.c]=makeWagon(p.u.color,p.u.symbol,'normal',{linkId:link,bonus:p.u.bonus})}sfx('land');await resolveBoard();if(!state.running)return;state.resolving=false;spawn();updateUI()}
function cellKey(x){return `${x.color}:${x.symbol}`}
function findMatches(){const out=new Set();for(let r=0;r<ROWS;r++){let c=0;while(c<COLS){let x=state.board[r][c];if(!isMatchable(x)){c++;continue}let k=cellKey(x),e=c+1;while(e<COLS&&isMatchable(state.board[r][e])&&cellKey(state.board[r][e])===k)e++;if(e-c>=MATCH)for(let i=c;i<e;i++)out.add(`${r},${i}`);c=e}}for(let c=0;c<COLS;c++){let r=0;while(r<ROWS){let x=state.board[r][c];if(!isMatchable(x)){r++;continue}let k=cellKey(x),e=r+1;while(e<ROWS&&isMatchable(state.board[e][c])&&cellKey(state.board[e][c])===k)e++;if(e-r>=MATCH)for(let i=r;i<e;i++)out.add(`${i},${c}`);r=e}}return out}
function isMatchable(x){return x&&(x.kind==='normal'||x.kind==='locked')}
function expandBonuses(set){let add=new Set(set);for(const k of [...set]){const [r,c]=k.split(',').map(Number),x=state.board[r][c];if(!x?.bonus)continue;if(x.bonus==='bomb'){for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++)if(inBounds(r+dr,c+dc))add.add(`${r+dr},${c+dc}`);sfx('boom')}if(x.bonus==='loco'){for(let cc=0;cc<COLS;cc++)add.add(`${r},${cc}`);sfx('whistle')}if(x.bonus==='clock'){state.slowPieces=Math.max(state.slowPieces,3);toast('🕐 Orologio: caduta rallentata per 3 pezzi')}}return add}
async function resolveBoard(){let chain=0;while(true){let m=findMatches();if(!m.size)break;chain++;state.comboMax=Math.max(state.comboMax,chain);m=expandBonuses(m);state.flash=new Set(m);render();sfx(chain>1?'combo':'match');if(chain>1)combo(chain);await sleep(180);let cleared=[];for(const k of m){const [r,c]=k.split(',').map(Number),x=state.board[r][c];if(!x)continue;if(x.kind==='locked'||x.kind==='normal'){cleared.push([r,c,x]);state.score+=x.kind==='locked'?350:90;state.board[r][c]=null}}
 damageAdjacent(cleared);state.flash.clear();await gravityAnimated();recount();updateUI();await sleep(80)}
 if(checkWin()){win();return} }
function damageAdjacent(cleared){const hit=new Set();for(const [r,c] of cleared)for(const [dr,dc] of [[1,0],[-1,0],[0,1],[0,-1]]){const rr=r+dr,cc=c+dc;if(!inBounds(rr,cc))continue;const x=state.board[rr][cc];if(x&&(x.kind==='obstacle'||x.kind==='breakable')&&!x.fixed)hit.add(`${rr},${cc}`)}for(const k of hit){const [r,c]=k.split(',').map(Number),x=state.board[r][c];x.hp--;state.shake.add(k);state.score+=120;if(x.hp<=0){state.board[r][c]=null;state.score+=300}}setTimeout(()=>state.shake.clear(),240)}
async function gravityAnimated(){let moved=true,guard=0;while(moved&&guard++<ROWS){moved=gravityStep();if(moved){render();await sleep(38)}}}
function gravityStep(){let moved=false;const seen=new Set();for(let r=ROWS-2;r>=0;r--)for(let c=0;c<COLS;c++){let x=state.board[r][c];if(!x||x.kind!=='normal'||seen.has(x.id))continue;if(x.linkId){const mates=[];for(let rr=Math.max(0,r-1);rr<=Math.min(ROWS-1,r+1);rr++)for(let cc=Math.max(0,c-1);cc<=Math.min(COLS-1,c+1);cc++){let y=state.board[rr][cc];if(y&&y.kind==='normal'&&y.linkId===x.linkId)mates.push([rr,cc,y])}if(mates.length===2){mates.forEach(v=>seen.add(v[2].id));const sorted=[...mates].sort((a,b)=>b[0]-a[0]);let can=mates.every(([rr,cc])=>rr+1<ROWS&&(state.board[rr+1][cc]===null||mates.some(([mr,mc])=>mr===rr+1&&mc===cc)));if(can){for(const [rr,cc] of sorted){state.board[rr+1][cc]=state.board[rr][cc];state.board[rr][cc]=null}moved=true}continue}}
 if(r+1<ROWS&&!state.board[r+1][c]){state.board[r+1][c]=x;state.board[r][c]=null;moved=true}}
 return moved}
function checkWin(){return state.locked<=0&&(state.cfg.level<11||state.obstacles<=0)&&(state.cfg.level<16||state.breakables<=0)}
function win(){state.running=false;state.resolving=false;frun=false;fscore=state.score;const stars=state.comboMax>=3?3:state.comboMax>=2?2:1;if(window.MimmoLives)window.MimmoLives.awardStarsBonus(stars);showOverlay('Tratta completata!',`Hai liberato tutti i vagoni. ${'★'.repeat(stars)}${'☆'.repeat(3-stars)}`,[['Continua',()=>{hideOverlay();completeLevel('falling')}],['Rigioca',()=>{hideOverlay();buildLevel(state.level)},'secondary']]);sfx('whistle')}
function gameOver(){
 state.running=false;state.resolving=false;sfx('boom');
 if(!window.MimmoLives){showOverlay('Fine corsa','Non c’è più spazio per far entrare una nuova coppia di vagoni.',[['Riprova',()=>{hideOverlay();buildLevel(state.level)}],['Percorso',()=>{hideOverlay();selectedMode='falling';buildMap('falling');show('mapScreen')},'secondary']]);return}
 const result=window.MimmoLives.loseLife();
 const exitToMap=()=>{selectedMode='falling';buildMap('falling');show('mapScreen')};
 if(result.lives<=0 && !window.MimmoLives.isRelax()){
   window.MimmoLives.showLockedOverlay({onResume:()=>buildLevel(state.level),onExit:exitToMap});
 } else {
   window.MimmoLives.showDefeatOverlay({title:'Fine corsa',text:'Non c’è più spazio per far entrare una nuova coppia di vagoni.',onRetry:()=>buildLevel(state.level),onExit:exitToMap});
 }
}
function showOverlay(title,text,buttons){const o=$('#bpOverlay');o.innerHTML=`<div class="bp-overlay-card"><h2>${title}</h2><p>${text}</p><div class="bp-overlay-actions"></div></div>`;const a=o.querySelector('.bp-overlay-actions');for(const [label,fn,cl] of buttons){const b=document.createElement('button');b.textContent=label;if(cl)b.className=cl;b.onclick=fn;a.appendChild(b)}o.classList.add('show');o.setAttribute('aria-hidden','false')}
function hideOverlay(){const o=$('#bpOverlay');o.classList.remove('show');o.setAttribute('aria-hidden','true')}
function togglePause(){if(!state.running)return;state.paused=!state.paused;if(state.paused)showOverlay('Pausa','Il treno aspetta.',['Riprendi',()=>{state.paused=false;hideOverlay();state.lastDrop=performance.now()}],['Percorso',()=>{state.paused=false;hideOverlay();selectedMode='falling';buildMap('falling');show('mapScreen')},'secondary']);else hideOverlay()}
function tutorialForLevel(){state.tutorialStep=0;if(state.level===1){toast('Abbina 4 vagoni con STESSO COLORE + STESSO SIMBOLO',3200)}else if(state.level===11)toast('Nuovo: elimina vicino agli ostacoli per danneggiarli',2600);else if(state.level===16)toast('Nuovo: i blocchi possono richiedere più colpi',2600);else if(state.level===21)toast('Nuovo: nei vagoni possono comparire bonus ferroviari',2600);else if(state.level===26)toast('Attenzione: iniziano i primi imprevisti di viaggio',2600)}
function toast(text,ms=2200){const h=$('#bpHint');h.textContent=text;h.classList.remove('show');void h.offsetWidth;h.classList.add('show');if(ms!==2400){setTimeout(()=>h.classList.remove('show'),ms)}}
function combo(n){const el=$('#bpCombo');el.textContent=`COMBO ×${n}`;el.classList.remove('show');void el.offsetWidth;el.classList.add('show')}
function updateUI(){recount();$('#fScore').textContent=String(state.score).padStart(7,'0');$('#fLevel').textContent=state.level;$('#fSignals').textContent=state.locked;$('#bpWorldLabel').textContent=`MONDO ${state.cfg.world}`;$('#bpLevelName').textContent=state.cfg.name;$('#bpGoalMini').textContent=`${state.locked} bloccati`;$('#fMessage').textContent=objectiveText();const st=typeof storyFor==='function'?storyFor(state.level):'';if(st)$('#fStory').textContent=st}
function objectiveText(){let p=[`${state.locked} vagoni bloccati`];if(state.cfg.level>=11)p.push(`${state.obstacles} ostacoli`);if(state.cfg.level>=16)p.push(`${state.breakables} blocchi`);return 'Libera '+p.join(' • ')}
function setWorld(){const bg=$('#bpWorldBg');bg.style.backgroundImage=`url("${WORLD_BG[state.cfg.world-1]}")`;$('#gameStation').textContent=WORLD_NAMES[state.cfg.world-1]}
function haptic(ms){try{navigator.vibrate?.(ms)}catch(e){}}
let ac=null;function tone(f,d=.05,type='square',gain=.035){try{ac=ac||new (window.AudioContext||window.webkitAudioContext)();const o=ac.createOscillator(),g=ac.createGain();o.type=type;o.frequency.value=f;g.gain.value=gain;o.connect(g);g.connect(ac.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,ac.currentTime+d);o.stop(ac.currentTime+d)}catch(e){}}
function sfx(k){if(k==='clack')tone(560,.035);else if(k==='land')tone(180,.05,'square',.045);else if(k==='match'){tone(760,.06,'sine',.045);setTimeout(()=>tone(980,.07,'sine',.035),35)}else if(k==='combo'){tone(880,.05,'sine',.05);setTimeout(()=>tone(1240,.08,'sine',.045),35)}else if(k==='boom')tone(95,.12,'sawtooth',.06);else if(k==='whistle'){tone(820,.18,'sine',.035);setTimeout(()=>tone(1040,.25,'sine',.03),90)}}
function ghostRow(){let r=state.active.r;while(valid(state.active,r+1,state.active.c,state.active.o))r++;return r}
function render(){ctx.clearRect(0,0,480,720);drawBoardBg();for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++){let x=state.board[r][c];if(x)drawCell(r,c,x,false)}if(state.active&&state.running){let gr=ghostRow();for(const p of posCells(state.active,gr,state.active.c,state.active.o))drawWagon(p.r,p.c,p.u,.18,true);drawConnector(state.active);for(const p of posCells(state.active))drawWagon(p.r,p.c,p.u,1,false,true)}if(state.fogTurns>0)drawFog()}
function drawBoardBg(){let g=ctx.createLinearGradient(0,0,0,720);g.addColorStop(0,'rgba(17,54,96,.92)');g.addColorStop(1,'rgba(4,19,42,.98)');ctx.fillStyle=g;ctx.fillRect(0,0,480,720);for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++){let x=c*CELL,y=r*CELL;ctx.fillStyle=(r+c)%2?'rgba(255,255,255,.028)':'rgba(255,255,255,.045)';roundRect(ctx,x+2,y+2,56,56,10);ctx.fill();ctx.strokeStyle='rgba(160,210,255,.12)';ctx.lineWidth=1;ctx.stroke()};ctx.strokeStyle='rgba(163,111,52,.52)';ctx.lineWidth=3;for(let c=0;c<COLS;c++){let x=c*CELL+18;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,720);ctx.stroke();ctx.beginPath();ctx.moveTo(x+24,0);ctx.lineTo(x+24,720);ctx.stroke()}}
function drawConnector(piece){const a=posCells(piece)[0],b=posCells(piece)[1];let ax=a.c*CELL+30,ay=a.r*CELL+31,bx=b.c*CELL+30,by=b.r*CELL+31;ctx.save();ctx.strokeStyle='#ffd76a';ctx.lineWidth=9;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(ax,ay);ctx.lineTo(bx,by);ctx.stroke();ctx.strokeStyle='#4b596a';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(ax,ay);ctx.lineTo(bx,by);ctx.stroke();ctx.restore()}
function drawCell(r,c,x,ghost=false){if(x.kind==='normal'||x.kind==='locked')drawWagon(r,c,x,1,false,false,x.kind==='locked');else if(x.kind==='obstacle')drawObstacle(r,c,x);else if(x.kind==='breakable')drawBreakable(r,c,x)}
function drawWagon(r,c,u,alpha=1,ghost=false,active=false,locked=false){const x=c*CELL+5,y=r*CELL+8,w=50,h=42,col=COLORS[u.color%COLORS.length];ctx.save();ctx.globalAlpha=alpha;if(active){ctx.shadowColor='#ffe66f';ctx.shadowBlur=16}let g=ctx.createLinearGradient(x,y,x,y+h);g.addColorStop(0,col.a);g.addColorStop(.58,col.b);g.addColorStop(1,col.rim);ctx.fillStyle=g;roundRect(ctx,x,y,w,h,9);ctx.fill();ctx.lineWidth=3;ctx.strokeStyle='#e9f6ff';ctx.stroke();ctx.fillStyle='rgba(255,255,255,.34)';roundRect(ctx,x+6,y+5,w-12,8,4);ctx.fill();ctx.fillStyle='#162b4a';ctx.beginPath();ctx.arc(x+12,y+h+4,6,0,Math.PI*2);ctx.arc(x+w-12,y+h+4,6,0,Math.PI*2);ctx.fill();ctx.fillStyle='#93a9c4';ctx.beginPath();ctx.arc(x+12,y+h+4,2.5,0,Math.PI*2);ctx.arc(x+w-12,y+h+4,2.5,0,Math.PI*2);ctx.fill();drawSymbol(ctx,u.symbol,x+w/2,y+25,13);if(u.bonus)drawBonus(ctx,u.bonus,x+w-9,y+9);if(locked){ctx.fillStyle='rgba(6,18,35,.28)';roundRect(ctx,x,y,w,h,9);ctx.fill();ctx.strokeStyle='#d9e1ec';ctx.lineWidth=2;ctx.setLineDash([5,4]);roundRect(ctx,x+3,y+3,w-6,h-6,7);ctx.stroke();ctx.setLineDash([]);drawLock(ctx,x+w-10,y+h-4)}if(state.flash.has(`${r},${c}`)){ctx.fillStyle='rgba(255,255,255,.7)';roundRect(ctx,x-2,y-2,w+4,h+8,11);ctx.fill()}ctx.restore()}
function drawSymbol(c,s,cx,cy,rad){c.save();c.fillStyle='#fff';c.strokeStyle='rgba(10,34,63,.65)';c.lineWidth=2.5;c.beginPath();if(SYMBOLS[s]==='circle')c.arc(cx,cy,rad,0,Math.PI*2);else if(SYMBOLS[s]==='triangle'){c.moveTo(cx,cy-rad);c.lineTo(cx+rad,cy+rad);c.lineTo(cx-rad,cy+rad);c.closePath()}else if(SYMBOLS[s]==='diamond'){c.moveTo(cx,cy-rad);c.lineTo(cx+rad,cy);c.lineTo(cx,cy+rad);c.lineTo(cx-rad,cy);c.closePath()}else if(SYMBOLS[s]==='square')c.rect(cx-rad*.78,cy-rad*.78,rad*1.56,rad*1.56);else{for(let i=0;i<10;i++){let a=-Math.PI/2+i*Math.PI/5,rr=i%2?rad*.46:rad;c.lineTo(cx+Math.cos(a)*rr,cy+Math.sin(a)*rr)}c.closePath()}c.fill();c.stroke();c.restore()}
function drawLock(c,x,y){c.save();c.fillStyle='#ffd453';c.strokeStyle='#8b5600';c.lineWidth=2;roundRect(c,x-9,y-7,18,15,4);c.fill();c.stroke();c.beginPath();c.arc(x,y-8,6,Math.PI,0);c.stroke();c.fillStyle='#6a4100';c.fillRect(x-1,y-2,2,6);c.restore()}
function drawBonus(c,type,x,y){c.save();c.fillStyle=type==='bomb'?'#111':type==='loco'?'#ffe054':'#eaf7ff';c.strokeStyle='#fff';c.lineWidth=2;c.beginPath();c.arc(x,y,8,0,Math.PI*2);c.fill();c.stroke();c.fillStyle=type==='bomb'?'#ffcc45':'#1c4c85';c.font='bold 10px sans-serif';c.textAlign='center';c.textBaseline='middle';c.fillText(type==='bomb'?'✹':type==='loco'?'➜':'◷',x,y+1);c.restore()}
function drawObstacle(r,c,x){let px=c*CELL+7,py=r*CELL+8;ctx.save();if(x.variant==='rock'){ctx.fillStyle='#737b8c';ctx.strokeStyle='#3e4656';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(px+7,py+36);ctx.lineTo(px+3,py+21);ctx.lineTo(px+14,py+6);ctx.lineTo(px+36,py+3);ctx.lineTo(px+48,py+19);ctx.lineTo(px+42,py+39);ctx.closePath();ctx.fill();ctx.stroke()}else{ctx.fillStyle='#f5f7fa';roundRect(ctx,px,py+8,46,28,6);ctx.fill();ctx.fillStyle='#e33b3b';for(let i=-8;i<50;i+=16){ctx.save();ctx.translate(px+i,py+8);ctx.rotate(-.55);ctx.fillRect(0,0,8,34);ctx.restore()}ctx.fillStyle='#58677b';ctx.fillRect(px+8,py+36,6,10);ctx.fillRect(px+34,py+36,6,10)}if(x.hp<90){ctx.fillStyle='#ffcf45';ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(px+40,py+8,10,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#553000';ctx.font='bold 11px sans-serif';ctx.textAlign='center';ctx.fillText(x.hp,px+40,py+12)}ctx.restore()}
function drawBreakable(r,c,x){let px=c*CELL+6,py=r*CELL+7;ctx.save();let g=ctx.createLinearGradient(px,py,px,py+45);g.addColorStop(0,'#d99a52');g.addColorStop(1,'#8f4d1f');ctx.fillStyle=g;ctx.strokeStyle='#5e3015';ctx.lineWidth=3;roundRect(ctx,px,py,48,45,5);ctx.fill();ctx.stroke();ctx.strokeStyle='#5f351c';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(px+6,py+7);ctx.lineTo(px+42,py+38);ctx.moveTo(px+42,py+7);ctx.lineTo(px+6,py+38);ctx.stroke();if(x.hp<=2){ctx.strokeStyle='#2f1a10';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(px+24,py+4);ctx.lineTo(px+20,py+18);ctx.lineTo(px+30,py+27);ctx.lineTo(px+25,py+43);ctx.stroke()}if(x.hp<=1){ctx.beginPath();ctx.moveTo(px+5,py+25);ctx.lineTo(px+18,py+21);ctx.lineTo(px+28,py+34);ctx.lineTo(px+44,py+31);ctx.stroke()}ctx.restore()}
function drawFog(){ctx.save();ctx.fillStyle='rgba(220,235,245,.17)';for(let i=0;i<5;i++){let r=Math.floor(state._rng()*ROWS),c=Math.floor(state._rng()*COLS);ctx.beginPath();ctx.arc(c*CELL+30,r*CELL+30,34,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawNext(){nctx.clearRect(0,0,nextCanvas.width,nextCanvas.height);if(!state.next)return;const tmp={...state.next,r:0,c:0,o:0};const cells=posCells(tmp);for(const [i,p] of cells.entries())drawMiniWagon(nctx,8+i*52,8,p.u)}
function drawMiniWagon(c,x,y,u){let col=COLORS[u.color];let g=c.createLinearGradient(x,y,x,y+35);g.addColorStop(0,col.a);g.addColorStop(1,col.b);c.fillStyle=g;c.strokeStyle='#fff';c.lineWidth=2;roundRect(c,x,y,44,34,8);c.fill();c.stroke();drawSymbol(c,u.symbol,x+22,y+18,8)}
function roundRect(c,x,y,w,h,r){c.beginPath();c.roundRect(x,y,w,h,r)}
function loop(t){try{if(state.running&&!state.paused&&!state.resolving&&state.active&&t-state.lastDrop>state.dropMs){if(!move(0,1))lockPiece();state.lastDrop=t}render();}catch(e){console.warn('[Mimmo Express] binari render error:',e);}raf=requestAnimationFrame(loop)}
function resize(){/* canvas uses fixed logical pixels and CSS scaling */}
function onPointerDown(e){if(!state.running||state.paused||state.resolving)return;state.inputStart={x:e.clientX,y:e.clientY,t:performance.now(),lx:e.clientX,ly:e.clientY,moved:false};canvas.setPointerCapture?.(e.pointerId);e.preventDefault()}
function onPointerMove(e){let s=state.inputStart;if(!s||!state.running||state.resolving)return;let dx=e.clientX-s.lx,dy=e.clientY-s.ly;if(Math.abs(dx)>28&&Math.abs(dx)>Math.abs(dy)){if(move(dx>0?1:-1,0)){s.lx=e.clientX;s.moved=true}}else if(dy>34&&Math.abs(dy)>Math.abs(dx)){if(move(0,1)){s.ly=e.clientY;s.moved=true}}e.preventDefault()}
function onPointerUp(e){let s=state.inputStart;if(!s)return;let dx=e.clientX-s.x,dy=e.clientY-s.y,dt=performance.now()-s.t;state.inputStart=null;if(!s.moved&&Math.abs(dx)<16&&Math.abs(dy)<16)rotate(1);else if(dy>75&&dt<280)hardDrop();e.preventDefault()}
canvas.addEventListener('pointerdown',onPointerDown);canvas.addEventListener('pointermove',onPointerMove);canvas.addEventListener('pointerup',onPointerUp);canvas.addEventListener('contextmenu',e=>e.preventDefault());
document.addEventListener('keydown',e=>{if(!$('#fallGame')?.classList.contains('active')||!window.MIMMO_BINARI_V22)return;if(['ArrowLeft','ArrowRight','ArrowDown','ArrowUp',' ','z','Z','x','X'].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft')move(-1,0);else if(e.key==='ArrowRight')move(1,0);else if(e.key==='ArrowDown')move(0,1);else if(e.key==='ArrowUp'||e.key==='x'||e.key==='X')rotate(1);else if(e.key==='z'||e.key==='Z')rotate(-1);else if(e.key===' ')hardDrop()});
$('#bpPause').onclick=togglePause;
// Keep current map navigation and sound button behavior from the main game.
const oldStart=window.startFalling; window.startFalling=function(level){try{frun=false}catch(e){} buildLevel(level)};
window.addEventListener('resize',resize);if(!raf)raf=requestAnimationFrame(loop);
})();
